### PR TITLE
Add History Query

### PR DESCRIPTION
**Pull request by Accelerater**
## What's the purpose of this PR

添加 通过配置的key对变更历史的查询

## Which issue(s) this PR fixes:
Fixe s#3195

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by JaredTan95** [comment]
pls sign the CLA :)

**Comment by JaredTan95** [comment]
and update the `CHANGES.md`

**Comment by Accelerater** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JaredTan95** [comment]
recheck

**Pull request closed without merging**
