### PR TITLE
Fix possiable NPE

### PR DESCRIPTION
**Pull request by lonre**
## What's the purpose of this PR

NPE in some cases

## Which issue(s) this PR fixes:
Fixes #

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by klboke** [comment]
Hello, can you briefly explain what scenarios will cause problems?

**Comment by lonre** [comment]
> Hello, can you briefly explain what scenarios will cause problems?

Hi, in some edge case, such as debugging for the config loading process, that will be longer than 1 minute, 

than the log expired and caused the NPE.

IMO, also we should keep all logs, it should not too much

**Review by klboke — COMMENTED** [review]
LGTM

**Review by klboke — APPROVED** [review]

**Comment by lonre** [comment]
> LGTM

@nobodyiam ping

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
