### PR TITLE
fix show-text-modal number display(#3821)

### LINKED ISSUE #3821: 整数精度展示问题
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
image
当配置的value值是较大整数时，保存和编辑时展示的整数是正确的，但是点击value弹出窗口查看的整数有精度丢失。

**To Reproduce**
1. 存储整数数组，[9587743934784070, 13246918697656345, 127525757991925097]
2. 点击发布。
3. 点击整数value值。
4. 查看value与实际整数值存在丢失问题。
5. http://106.54.227.205/config.html?#/appid=defaultAppId 点击链接查看

**Expected behavior**
整数值展示正确。

**Screenshots**
image

### Additional Details & Logs

- Version
- 当前使用版本基于1.7.1，在首页提供的demo链接中重现了该问题。
- Error logs
- Configuration
- Platform and Operating System

### PR DESCRIPTION
**Pull request by CalebZYC**
## What's the purpose of this PR

修复整数精度展示问题

## Which issue(s) this PR fixes:
Fixes #3821

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by CalebZYC** [comment]
修改效果如下：
image
image
image
image
image
image
image
image

**Comment by JaredTan95** [comment]
recheck

**Comment by JaredTan95** [comment]
hi，thanks your contributions again. But, do you have time to sign the CLA by leaving a "I have read the CLA Document and I hereby sign the CLA" comment.:-P

**Comment by CalebZYC** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JaredTan95** [comment]
please fix conflicts.

**Pull request closed without merging**
