### PR TITLE
add apollo portal demo with public server.

### PR DESCRIPTION
**Pull request by JaredTan95**

### CODE REVIEW

**Comment by nobodyiam** [comment]
非常感谢！后续等0.11.0发布了，可以考虑更新一版~

**Comment by JaredTan95** [comment]
👌

**Comment by nobodyiam** [comment]
貌似目前部署的版本还没有包含 #1002 这个PR，外网环境访问有些慢。。有空的时候帮忙更新一下吧。。

**Comment by nobodyiam** [comment]
恩。。。是单独的quick start项目，等0.11.0发布了我再更新一把镜像吧

**Comment by JaredTan95** [comment]
👌




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            jian.tan
                            
                            
                                
                                    邮箱：jian.tan@daocloud.io
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 07/23/2018 23:35, Jason Song wrote: 恩。。。是单独的quick start项目，等0.11.0发布了我再更新一把镜像吧

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ctripcorp/apollo","title":"ctripcorp/apollo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ctripcorp/apollo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nobodyiam in #1280: 恩。。。是单独的quick start项目，等0.11.0发布了我再更新一把镜像吧"}],"action":{"name":"View Pull Request","url":"https://github.com/ctripcorp/apollo/pull/1280#issuecomment-407100986"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ctripcorp/apollo/pull/1280#issuecomment-407100986",
"url": "https://github.com/ctripcorp/apollo/pull/1280#issuecomment-407100986",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ctripcorp/apollo] add apollo portal demo with public server. (#1280)",
"sections": [
{
"text": "",
"activityTitle": "**Jason Song**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nobodyiam",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ctripcorp/apollo\",\n\"issueId\": 1280,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ctripcorp/apollo/pull/1280#issuecomment-407100986"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 359294929\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by nobodyiam** [comment]
@JaredTan95 

0.11.0的docker quick start image已经更新，执行`docker pull nobodyiam/apollo-quick-start`即可拉到最新image，麻烦有空的时候更新一下吧~

**Comment by JaredTan95** [comment]
@nobodyiam Updated completely.

**Comment by nobodyiam** [comment]
@JaredTan95 Thanks a lot!

**Pull request merged**
