### PR TITLE
fix the issue that access key doesn't work if appid passed is in different case

### LINKED ISSUE #3626: 客户端配置的AppId大小写与服务端不一致时可越过accessKey检查而直接获取到配置
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

由于config service大小写不敏感，而导致客户端配置的AppId大小写与服务端不一致时可越过accessKey检查而直接获取到配置；
或直接通过postman等工具获取到配置文件；

**复现**

通过如下步骤可以复现：

1. apollo开启访问秘钥
2. 客户端配置 -Dapp.id={此处与portal配置的大小写不一致}
3. 客户端不配置 accessKey
4. 启动应用可以成功获取到配置（或使用postman直接请求）

**期望**

返回401而不是配置

**截图**

### 额外的细节和日志

- 版本：服务端1.8.1；客户端1.8.0

### PR DESCRIPTION
**Pull request by nobodyiam**
## What's the purpose of this PR

fix the issue that access key doesn't work if appid passed is in different case

## Which issue(s) this PR fixes:
Fixes #3626

## Brief changelog

Use tree set with CASE_INSENSITIVE_ORDER comparator.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.

### CODE REVIEW

**Comment by nisiyong** [comment]
It looks good to me, but how we avoid this situation next time. 
It seems that there had serval issues about sensitive appId  previously, do we need some common utils to fix the same issues?

**Comment by nobodyiam** [comment]
> It seems that there had serval issues about sensitive appId previously, do we need some common utils to fix the same issues?

You are right, there have been several case sensitive issues. Previously we also have this issue for namespace names, and we fixed that via NamespaceUtil#normalizeNamespace.
Maybe we could also write an AppUtil to normalize the app id?

https://github.com/ctripcorp/apollo/blob/943bbb4d56bd9d3bbec291ea17136099a3a60b7c/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/util/NamespaceUtil.java#L28-L40

**Comment by nisiyong** [comment]
@nobodyiam I think we can merge this PR first, and create a new issue to build `AppUtil`.

**Review by nisiyong — COMMENTED** [review]
LGTM

**Review by nisiyong — APPROVED** [review]

**Pull request merged**
