### PR TITLE
Add unit tests for com.ctrip.framework.apollo.core.utils.StringUtils

### PR DESCRIPTION
**Pull request by JohnLBergqvist**
I've analysed your codebase and noticed that `com.ctrip.framework.apollo.core.utils.StringUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

### CODE REVIEW

**Comment by lepdou** [comment]
Thank you very much for your contribution. 
And Apollo welcomes more community developer to build together. 😁

**Comment by lepdou** [comment]
Diffblue is so cool. I would know more about it.

**Comment by nobodyiam** [comment]
Looks cool!

**Comment by JohnLBergqvist** [comment]
@lepdou Many thanks for merging the PR. If you'd like to know more, you can contact us here: https://www.diffblue.com/contact

**Pull request merged**
