### PR TITLE
移除方法名中的Cat

### PR DESCRIPTION
**Pull request by powerYao**
那次只改了V2中的代码，现发现NotificationController.java也有同样的代码。

### CODE REVIEW

**Comment by nobodyiam** [comment]
the logWatchedKeysToCat method name is fixed in a previous pr - #688 

as to the null check for namespace, I don't think it will be null, can you give an exact case?

**Comment by powerYao** [comment]
NotificationController.java 还没有改，null检查如果一定不为空，可以不用处理，谢谢

**Comment by nobodyiam** [comment]
[NotificationController.java](https://github.com/ctripcorp/apollo/blob/master/apollo-configservice/src/main/java/com/ctrip/framework/apollo/configservice/controller/NotificationController.java#L162)昨天在 #688 中已经改了~

config controller中的namespace参数一定是不为空的，因为是从path variable中映射出来的~

Thanks for your pull request anyway!

**Comment by powerYao** [comment]
好的，哈哈

**Pull request closed without merging**
