### PR TITLE
openapi support create and load cluster info

### PR DESCRIPTION
**Pull request by Joe798**
openapi support create and load cluster info

### CODE REVIEW

**Comment by nobodyiam** [comment]
@Joe798

**Comment by DrmagicE** [comment]
Could you  please update OpenAPI doc in Wiki? I can't find  documents about how to use OpenAPI to create a cluster. @nobodyiam

**Comment by nobodyiam** [comment]
@DrmagicE done

**Comment by DrmagicE** [comment]
@nobodyiam  It seems miss the envs part in url.
image

**Comment by nobodyiam** [comment]
@DrmagicE Thanks for your tip, it's fixed now.

**Pull request merged**
