### PR TITLE
Auto Updating Spring Placeholder Values

### PR DESCRIPTION
**Pull request by nobodyiam**
# Auto Updating Spring Placeholder Values

## 1. Features
Spring placeholder values will now be auto updated when new configs are released in Apollo.

### 1.1 `@Value` Placeholders

Full support is provided for:

1. `@Value` placeholders annotated on fields
2. `@Value` placeholders annotated on methods
3. `@Value` placeholders with Spring Expression Language

For example, the following 3 fields can all be auto updated when the corresponding config is changed:

```java
public class TestJavaConfigBean {

  @Value("${timeout:100}")
  private int timeout;
  private int batch;
  @Value("#{new java.text.SimpleDateFormat('${dateFormat}').parse('${dateProperty}')}")
  private Date someDate;

  @Value("${batch:200}")
  public void setBatch(int batch) {
    this.batch = batch;
  }

  public int getTimeout() {
    return timeout;
  }

  public int getBatch() {
    return batch;
  }

  public Date getSomeDate() {
    return someDate;
  }
}

@Configuration
@EnableApolloConfig
public class AppConfig {
  @Bean
  TestJavaConfigBean testJavaConfigBean() {
    return new TestJavaConfigBean();
  }
}
```

Sample Configurations:

```properties
timeout=1000
batch=200
dateFormat=yyyy-MM-dd HH:mm:ss.SSS
dateProperty=2018-02-23 20:01:02.123
```

We also provide limited support for nested placeholders.

For example, with the following configurations and program:

1. `batch` equals to `normalBatch` at first, so the initial nestedProperty equals to `1000`
2. When `batch` is changed to `specialBatch`, then the nestedProperty field will be changed to `5000`
3. However, if we don't change `batch` config and change `normalBatch` to `5000` instead, then the nestedProperty won't be auto updated

```properties
batch=normalBatch
normalBatch=1000
specialBatch=5000
```

```java
public class TestNestedPropertyBean {

  @Value("${${batch}}")
  private int nestedProperty;

  public int getNestedProperty() {
    return nestedProperty;
  }
}
```

### 1.2 XML Placeholders

Full support is provided for placeholders for property field.

For example, the following 3 fields can all be auto updated when the corresponding config is changed:

```java
public class TestXmlBean {
  private int timeout;
  private int batch;
  private Date someDate;

  public void setTimeout(int timeout) {
    this.timeout = timeout;
  }

  public int getTimeout() {
    return timeout;
  }

  public void setBatch(int batch) {
    this.batch = batch;
  }

  public int getBatch() {
    return batch;
  }

  public void setSomeDate(Date someDate) {
    this.someDate = someDate;
  }

  public Date getSomeDate() {
    return someDate;
  }
}
```

Xml Config:

```xml
<apollo:config/>

<bean class="com.ctrip.framework.apollo.spring.demo.TestXmlBean">
    <property name="timeout" value="${timeout:100}"/>
    <property name="batch" value="${batch:200}"/>
    <property name="someDate" value="#{new java.text.SimpleDateFormat('${dateFormat}').parse('${dateProperty}')}"/>
</bean>
```

Sample Configurations:

```properties
timeout=1000
batch=200
dateFormat=yyyy-MM-dd HH:mm:ss.SSS
dateProperty=2018-02-23 20:01:02.123
```

We also provide limited support for nested placeholders, the same as `@Value` placeholders.

## 2. Configuration

This auto update feature is turned on by default, you could turn off this feature by:

1. Specify `apollo.autoUpdateInjectedSpringProperties=false` in System Properties
    For example, you may pass `-Dapollo.autoUpdateInjectedSpringProperties=false` when starting the Java program

2. Specify `apollo.autoUpdateInjectedSpringProperties=false` in META-INF/app.properties
    For example, 
    ```properties
    app.id=SampleApp
    apollo.autoUpdateInjectedSpringProperties=false
    ```

> If `apollo.autoUpdateInjectedSpringProperties` is specified in both System Properties and META-INF/app.properties, then the one specified in System Properties wins.

### CODE REVIEW

**Comment by zollty** [comment]
Great job!

**Comment by seven7ma** [comment]
Perfect!

**Comment by caoyang5858** [comment]
nice

**Comment by wuxin402** [comment]
spring 注入的方式还是不支持热配置，要用apollo自带的那种方式才行

**Comment by beareserve** [comment]
嗯！！

**Comment by caoyang5858** [comment]
您好，您的邮件我已收到

**Pull request merged**
