### PR TITLE
Add kubernetes native service discovery support and helm chart templates

### LINKED ISSUE #3054: [Feature Proposal] Apollo with Kubernetes Service Discovery
**Is your feature request related to a problem? Please describe.**
Apollo作为非常底层的基础设施，对可用性要求非常高，所以从设计之初就极力降低对外部的依赖，其中就包括通过内置Eureka来实现服务发现：

ServerArchitecture

上图是Apollo的整体架构，可以看到Eureka在其中担当了非常重要的角色。
该架构在非K8S环境下比较自然，运行良好。不过在K8S环境下，由于需要配置`eureka.service.url`，所以采用了statefulset来部署config service，一方面带来了运维的复杂度，另一方面也脱离了k8s自身的服务发现体系，无法享受生态红利，社区中对此也有一些讨论：#2666，#2903。

**Describe the solution you'd like**
当部署在Kubernetes环境中，可以借助于K8S原生的Service、健康检查等来实现服务发现和通信，从而可以一方面简化部署复杂度，另一方面可以享受生态红利，如Istio。

image

如上图所示，Eureka已经从整体架构中消失，取而代之的是Kubernetes的Service。为了减少对Client和Portal的影响，依然保留了Meta Service角色负责Config Service和Admin Service的寻址，区别在于在K8S环境下，返回的并不是单节点的地址，而是对应的服务内部域名，客户端在DNS解析后最终通过clusterIp来访问服务。

**Describe alternatives you've considered**
上述方案最终通过clusterIp来访问服务，对客户端而言，访问的始终是同一个IP，客户端不再有负载均衡逻辑，灵活度有所降低，不过优点是能够无缝对接生态体系，如Istio。
另一种方案是使用[spring-cloud-kubernetes](https://spring.io/projects/spring-cloud-kubernetes)，优点是客户端能够获取到Pod列表从而保留负载均衡逻辑，不过缺点是对一些生态工具的引入会有影响。

### PR DESCRIPTION
**Pull request by nobodyiam**
## What's the purpose of this PR

Add kubernetes native service discovery support to simplify the deployment complexity of apollo and enable the possibliity to integrate with other kubernetes tooling ,such as Istio.

## Which issue(s) this PR fixes:
Fixes #3054 

## Brief changelog

1. Add KubernetesDiscoveryService implementation that skips any service discovery and just return what is configured
2. Add helm charts for configservice, adminservice and portal which leverage the kubernetes native service discovery

### 1. Add Apollo Helm Chart Repository

```bash
$ helm repo add apollo http://ctripcorp.github.io/apollo/charts
$ helm search repo apollo
```

### 2. Install apollo-configservice and apollo-adminservice

Suppose the address of ApolloConfigDB is `1.2.3.4`, user name/password is `apollo`, then 

```bash
$ helm install apollo-service-dev \
    --set configdb.host=1.2.3.4 \
    --set configdb.userName=apollo \
    --set configdb.password=apollo \
    --set configdb.service.enabled=true \
    --set configService.replicaCount=1 \
    --set adminService.replicaCount=1 \
    apollo/apollo-service
```

### 3. Install apollo-portal

Suppose the address of ApolloPortalDB is `1.2.3.4`, user name/password is `apollo`, the service name of apollo-configservice is `apollo-service-dev-apollo-configservice`, then

```bash
$ helm install apollo-portal \
    --set portaldb.host=1.2.3.4 \
    --set portaldb.userName=apollo \
    --set portaldb.password=apollo \
    --set portaldb.service.enabled=true \
    --set config.envs="dev" \
    --set config.metaServers.dev=http://apollo-service-dev-apollo-configservice:8080 \
    --set replicaCount=1 \
    apollo/apollo-portal
```

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.

### CODE REVIEW

**Comment by stheart** [comment]
$ helm repo add apollo http://ctripcorp.github.io/apollo/charts
$ helm search repo apollo
执行完上述命令后显示为：No results found
http://ctripcorp.github.io/apollo/charts-------这个地址为啥是404

**Comment by nobodyiam** [comment]
@stheart 地址是正确的，看下是否是你本地的网络访问有问题？可以尝试下载下面的文件试试
http://ctripcorp.github.io/apollo/charts/index.yaml

**Comment by stheart** [comment]
> @stheart 地址是正确的，看下是否是你本地的网络访问有问题？可以尝试下载下面的文件试试
> http://ctripcorp.github.io/apollo/charts/index.yaml
谢谢，地址没问题，我helm版本太低，不支持helm search repo

**Comment by stheart** [comment]
> @stheart 地址是正确的，看下是否是你本地的网络访问有问题？可以尝试下载下面的文件试试
> http://ctripcorp.github.io/apollo/charts/index.yaml

地址没问题，是我helm版本低了，不支持helm search repo

**Pull request merged**
