### PR TITLE
Feature: sort table

### PR DESCRIPTION
**Pull request by bigflybrother**
https://github.com/ctripcorp/apollo/issues/2516

### CODE REVIEW

**Comment by JaredTan95** [comment]
Make sense to me, we will take a look soon.

**Comment by bigflybrother** [comment]
71572343978_ pic_hd

**Comment by nobodyiam** [comment]
It looks like a good idea to use last modified time to sort the release status...

**Comment by JaredTan95** [comment]
> It looks like a good idea to use last modified time to sort the release status...

Or both supported? 

What do you think? @bigflybrother

**Comment by JaredTan95** [comment]
Tested in my local env, looks good to me.

hope your more contributions to UI. @bigflybrother

**Pull request merged**
