### PR TITLE
Fix #2328

### LINKED ISSUE #2328: 项目启动报WARN
## 日志
2019-06-12 12:04:59.670|/|WARN |main|o.s.b.c.p.PropertySourcesDeducer|Multiple PropertySourcesPlaceholderConfigurer beans registered [propertySourcesPlaceholderConfigurer, org.springframework.context.support.PropertySourcesPlaceholderConfigurer], falling back to Environment

## Apollo Client  => ConfigPropertySourcesProcessor
image

## Spring boot  => org.springframework.boot.context.properties.PropertySourcesDeducer
image

## 
这个能修复下吗？ 项目使用 sentry， 每次项目启动 都收到 邮件提醒。

### PR DESCRIPTION
**Pull request by lonre**
case: beanDefinition of the bean defined in Configuration annotated class
in this case, the `beanDefinition.getBeanClassName()` and `beanClass.getName()` is not match

## What's the purpose of this PR

XXXXX

## Which issue(s) this PR fixes:
Fixes #

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

### CODE REVIEW

**Comment by nobodyiam** [comment]
Would you please describe an actual case for this issue?

**Comment by lonre** [comment]
> Would you please describe an actual case for this issue?

Spring Boot has a HIGHEST_PRECEDENCE `PropertyPlaceholderAutoConfiguration`, which defines a bean `propertySourcesPlaceholderConfigurer` of class `PropertySourcesPlaceholderConfigurer`, the beanDefinition's `getBeanClassName` of `propertySourcesPlaceholderConfigurer` is `PropertyPlaceholderAutoConfiguration`, not `PropertySourcesPlaceholderConfigurer`

@nobodyiam

**Comment by nobodyiam** [comment]
> > Would you please describe an actual case for this issue?
> 
> Spring Boot has a HIGHEST_PRECEDENCE `PropertyPlaceholderAutoConfiguration`, which defines a bean `propertySourcesPlaceholderConfigurer` of class `PropertySourcesPlaceholderConfigurer`, the beanDefinition's `getBeanClassName` of `propertySourcesPlaceholderConfigurer` is `PropertyPlaceholderAutoConfiguration`, not `PropertySourcesPlaceholderConfigurer`
> 
> @nobodyiam

Is there a detailed steps to duplicate the issue? I tried the [springBootDemo](https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo) but seems failed to duplicate this issue.

**Comment by lonre** [comment]
> > > Would you please describe an actual case for this issue?
> > 
> > 
> > Spring Boot has a HIGHEST_PRECEDENCE `PropertyPlaceholderAutoConfiguration`, which defines a bean `propertySourcesPlaceholderConfigurer` of class `PropertySourcesPlaceholderConfigurer`, the beanDefinition's `getBeanClassName` of `propertySourcesPlaceholderConfigurer` is `PropertyPlaceholderAutoConfiguration`, not `PropertySourcesPlaceholderConfigurer`
> > @nobodyiam
> 
> Is there a detailed steps to duplicate the issue? I tried the [springBootDemo](https://github.com/ctripcorp/apollo/tree/master/apollo-demo/src/main/java/com/ctrip/framework/apollo/demo/spring/springBootDemo) but seems failed to duplicate this issue.

Hi, just minimal demo generated from https://start.spring.io with apollo-client-config-data dependency
```
<dependency>
	<groupId>com.ctrip.framework.apollo</groupId>
	<artifactId>apollo-client-config-data</artifactId>
	<version>1.9.0-SNAPSHOT</version>
</dependency>
```

[demo.zip](https://github.com/ctripcorp/apollo/files/6936106/demo.zip)

@nobodyiam

**Review by nobodyiam — CHANGES_REQUESTED** [review]
Thanks, please also update the changes.md

**Comment by lonre** [comment]
> Thanks, please also update the changes.md

@nobodyiam Done

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
